server:
  port: 8082

spring:
  application:
    name: smallmall-admin
  profiles:
    active: dev #默认为开发环境

mybatis-plus:
  mapper-locations:
    - classpath*:com/**/mapperxml/*.xml
    - classpath:dao/*.xml

