server:
  port: 8082

spring:
  application:
    name: smallmall-admin
  profiles:
    active: dev #默认为开发环境
  servlet:
    multipart:
      enabled: true #开启文件上传  MINIO
      max-file-size: 10MB #限制文件上传大小为10M  MINIO

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: P36mHsG0vHXmfVC$HwvRhlWBNy&Jg811 #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头

redis:
  database: smallmall
  key:
    admin: 'ums:admin'
    resourceList: 'ums:resourceList'
  expire:
    common: 86400 # 24小时

mybatis-plus:
  mapper-locations:
    - classpath*:com/**/mapperxml/*.xml
    - classpath:dao/*.xml

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /admin/info
      - /admin/logout
      - /minio/upload

minio:
  endpoint: http://47.99.113.23:9090 #MinIO服务所在地址
  bucketName: smallmall #存储桶名称
  accessKey: minioadmin #访问的key
  secretKey: minioadmin #访问的秘钥