spring:
  datasource:
    url: jdbc:mysql://47.99.113.23:3306/small_mall?useUnicode=true&characterEncoding=utf8&useCursorFetch=true&defaultFetchSize=500&allowMultiQueries=true&rewriteBatchedStatements=true&useSSL=false
    username: root
    password: root


